---
title: "Tilbudsavis - ChatGPT Prompts"
author: "Christian Kruse"
date: "`r Sys.Date()`"
output: html_document
---

div.main-container {
  max-width: 1600px !important;
}

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
options(scipen=999)
```

# Tilbudsavis - ChatGPT Prompts

```{r}

if (!require(pacman)) { install.packages("pacman") }
pacman::p_load(pushoverr,
               dplyr,
               tidyr,
               lubridate,
               scales,
               httr,
               ggplot2,
               rPref,
               jsonlite,
               glue)

```


```{r warning=FALSE,message=FALSE,include=FALSE}
readRenviron(path = "Renviron.site")
```

```{r}

keywords = c("skyr",
             "yoghurt",
             "bilka",
             "tun",
             "cola",
             "pepsi",
             "oksekød",
             "pizza",
             "rugbrød",
             "slik",
             "pølser",
             "lego",
             "lotus",
             "vitamin",
             "legetøj",
             # "ninjago",
             "pølser",
             "switch",
             "playstation",
             "ps5",
             "chokolade",
             "opbevaring",
             "tandpasta",
             "neutral",
             "slik",
             "kaffe",
             "laks"
             )

df_etilbudsavisen = do.call("rbind",lapply(keywords,function (keyword) {
  message(keyword)
  tryCatch(expr = {
  url = glue("https://etilbudsavis.dk/api/squid/v2/offers/search?query={keyword}&r_lat=55.7715601&r_lng=12.4943525&r_radius=30000&r_locale=da_DK&limit=100&offset=0")
  api_url = utils::URLencode(url)
  api_result = httr::GET(api_url)
  api_json = rawToChar(api_result$content)
  result = jsonlite::fromJSON(api_json)
  
  temp_df = result %>% 
    dplyr::select(heading,description,run_from,run_till,pricing) %>% 
    unnest_wider(pricing) %>% 
    dplyr::select(-pre_price,-currency) 
  
  dealer_dictionary = result$dealer %>% dplyr::select(name) 
  quantity_dictionary_unit = result$quantity$unit$symbol
  quantity_dictionary_size = result$quantity$size$to
  
  temp_df %>% 
    bind_cols(dealer_dictionary) %>% 
    dplyr::mutate(size=quantity_dictionary_size,
                  unit=quantity_dictionary_unit) %>% 
    dplyr::mutate(run_from=ymd(substr(run_from,start = 1,stop = 10))) %>% 
    dplyr::mutate(run_till=ymd(substr(run_till,start = 1,stop = 10))) %>% 
    filter(run_from<=Sys.Date()) %>% 
    filter(run_till>=Sys.Date()) %>% 
    # filter(!name %in% c("Harald Nyborg","Kop & Kande","Elgiganten","Lidl","Min Købmand","Imerco","Skousen","LET-KØB")) %>% 
    dplyr::mutate(name_full=name) %>% 
    dplyr::mutate(name=recode(name,
                              "føtex"="F",
                              "Netto"="N",
                              "Irma"="I",
                              "Coop365"="C",
                              "MENY"="M",
                              "SuperBrugsen"="SB",
                              "Kvickly"="K",
                              "Bilka"="B",
                              "REMA 1000"="R",
                              "Harald Nyborg"="HN",
                              "Dagli'Brugsen"="DB",
                              "SPAR"="S"),
                  keyword=keyword)
    
  },error=function(e) {
    data.frame()
  })
})) %>% 
  distinct() %>% 
  # dplyr::select(-run_from,-run_till) %>% 
  unite(size,size,unit,sep = " ")

```

```{r}
df_etilbudsavisen %>% DT::datatable(.,filter="top")
```

```{r}
openxlsx::write.xlsx(x = df_etilbudsavisen,file = "df_etilbudsavisen.xlsx")
```


```{r}
common_intro = glue("
           You are an expert in examining shopping deals.
           You will be provided a table of shopping offers in this format: 
           1) Store (F = Føtex, N = Netto, C = Coop365, M = Meny, SB = SuperBrugsen, K = Kvickly, B = Bilka, S = Spar), 
           2) Heading, 
           3) Price in Danish kroner, 
           4) Size. 
           
           List in bullet-point format all deals in the order of:
           1) The store, writing out the full name from the abbreviation, 
           2) Sub-bullet-points of each offer in the format of Topic: Item Name, Price, Content.  
           
           An example would be:
            Netto:
            - Skyr, 1000g, 20 kr.
            - Tun, 140g, 12 kr.
           
           Do not write any introducing or conclusion text. 
           
           The topics are:\n\n")
```

# Skyr

```{r results='asis'}
msg = df_etilbudsavisen %>% 
  filter(keyword=="skyr") %>% 
  dplyr::mutate(text=glue("{name}: {heading}, {description},{price} kr.,{size}")) %>% 
  pull(text) %>% 
  paste(.,collapse="\n")
msg = glue("{common_intro}",
           "1) Skyr",
           "\n\n{msg}")
msg
```

# Legetøj

```{r results='asis'}
msg = df_etilbudsavisen %>% 
  filter(keyword %in% c("lego","legetøj","switch","ps5","playstation")) %>% 
  dplyr::mutate(text=glue("{name}: {heading}, {description},{price} kr.,{size}")) %>% 
  pull(text) %>% 
  paste(.,collapse="\n")
msg = glue("{common_intro}",
           "1) Legetøj, gaming, nintendo, switch, playstation",
           "\n\n{msg}")
msg
```

# Oksekød

```{r results='asis'}

msg = df_etilbudsavisen %>% 
  filter(keyword %in% c("oksekød")) %>% 
  dplyr::mutate(text=glue("{name}: {heading}, {description},{price} kr.,{size}")) %>% 
  pull(text) %>% 
  paste(.,collapse="\n")
msg = glue("{common_intro}",
           "1) Oksekød",
           "\n\n{msg}")
msg


```

# Bilka ToGo

```{r}

msg = df_etilbudsavisen %>% 
  filter(name=="B") %>% 
  dplyr::mutate(text=glue("{heading}; {price} kr.; {size}")) %>% 
  pull(text) %>% 
  paste(.,collapse="\n")

bilka_intro = glue("
           You are an expert in examining shopping deals.
           You will be provided as lines of shopping offers each in this format: 
           - Title; Price in Danish kroner; Size. 
           
           Please propose a shopping list for a family to have breakfast, lunch, and dinners for 14 days.
           The list should be separated into:
           1) Food
           2) Necessities
           3) Child-oriented offers
           4) Treats
           
           List in bullet-point format all relevant deals in the order of:
           1) Each relevant offer with amount to buy in the format of Topic: Item Name, Price, Content.  
           
           An example would be:
            - Skyr, 1000g, 20 kr., 4 units
            - Tun, 140g, 12 kr., 3 units
           
           Do not write any introducing or conclusion text. 
           
           The deals are:\n\n")
msg = glue("{bilka_intro}",
           "\n\n{msg}")
msg

```

