on:
  push:
     branches:
       - main
  schedule:
    - cron:  '1 0 * * *'

name: pushoverr-tilbudsavis

jobs:
  bookdown:
    name: pushoverr
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Renviron
      #   run: echo $'PUSHOVER_APPKEY=${{ secrets.PUSHOVER_APPKEY }}\nPUSHOVER_USERKEY=${{ secrets.PUSHOVER_USERKEY }}\CHATGPTAPIKEY=${{ secrets.CHATGPTAPIKEY }}' >> Renviron.site
      - name: Render Book from Action
        uses: ckrusemd/rmarkdown-action@v0.21
        with:
           input_file: index.Rmd
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: _book # optional
        path: _book # optional
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _book
        user_name: 'GitHub Actions'
        user_email: ${{ secrets.EMAIL }}
        allow_empty_commit: false
        keep_files: true
        force_orphan: true
