on:
  push:
     branches:
       - master
  schedule:
    - cron:  '1 0 * * *'

name: pushoverr-tilbudsavis

jobs:
  bookdown:
    name: pushoverr
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Renviron
        run: echo $'PUSHOVER_APPKEY=${{ secrets.PUSHOVER_APPKEY }}\nPUSHOVER_USERKEY=${{ secrets.PUSHOVER_USERKEY }}\nFREDAPIKEY=${{ secrets.FREDAPIKEY }}' >> Renviron.site
      - name: Render Book from Action
        uses: ckrusemd/rmarkdown-action@v0.18
        with:
           input_file: index.Rmd
